name: "Build and lint"

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v30
      - uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/flake.lock', '**/*.nix', '**/Cargo.lock') }}
      - name: Linting
        run: nix flake check
      - name: Building
        run: nix build
